import type { Metadata } from "next";
import { Staatliches as Staat } from "next/font/google";
import "./globals.css";

import { cn } from "@/lib/utils"

const font_staat = Staat({
  subsets: ['latin'],
  variable: "--font-sans",
  weight: "400",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head />
      <body
        style={{backgroundImage: `url('/BackgroundBlur.png')`, height: "100%", width: "100%", backgroundPosition: "bottom", backgroundSize: "cover"}} 
        className={cn(
          "min-h-screen bg-background font-sans antialiased"
        )}
      >
        {children}
      </body>
    </html>
  );
}
